### ISSUE TITLE
[6.8]Invincibility Star

### ISSUE THREAD

**Issue by Firomaeor** [INF19IT2/2d-Jump-n-Run-SE#119]
Der Stern soll den Spieler für eine Zeit von 5 Sekunden unverwundbar machen
Ein Stern ist ein Objekt, dass bei Berührung in der Spielumgebung aktiviert wird (Kein Aufbewahren in einem Inventory)

**Comment by SammyDerksen** [comment]
Der Spieler braucht eine Animation, solange der unverwundbar ist
