### ISSUE TITLE
Start Game by Pressing "Start/Level"

### ISSUE THREAD

**Issue by MrSteelTitan** [INF19IT2/2d-Jump-n-Run-SE#14]
- Change button name from "Level-Menu" to "Start/Level"
- Start Game by Pressing "Start/Level" instead of pressing Options

**Comment by Na1k** [comment]
There is no "Level" yet, just the testing environment (also see  #5).

**Comment by MrSteelTitan** [comment]
I just checked #5 an noticed an error of my part:
"the Testing-Enviroment should not start by pressig "Options" but by pressing "Level-Menu", this Issue fixes it.

**Comment by rxt30** [comment]
Merged in #16
