### ISSUE TITLE
Create an Escape Menu in the test-enviroment

### ISSUE THREAD

**Issue by MrSteelTitan** [INF19IT2/2d-Jump-n-Run-SE#15]
The ESC-Menu is triggered by hitting "ESC"
It has the following Buttons:
- "Continue" (Closes the ESC-Menu and continues the test-environment)
- "Restart" (Restarts the test-environment)
- "Back to Menu" (ends the test-environment and opens the Menu)
- "Options" (No function yet)

The ESC-Menu can also be closed by hitting the "ESC" again. It has the same function as the button "Continue"

**Comment by DerNoob24** [comment]
done with the merge of branch "Esc_Menu" in master Branch
