### ISSUE TITLE
Adjust Menu to the Mockup 

### ISSUE THREAD

**Issue by rxt30** [INF19IT2/2d-Jump-n-Run-SE#27]
https://cdn.discordapp.com/attachments/774220713019310100/779276080141959188/unknown.png

**Comment by DerNoob24** [comment]
https://cdn.discordapp.com/attachments/774220713019310100/779308318061494282/Adobe_Xd_2020-11-20_12-22-11-1.m4v

**Comment by Firomaeor** [comment]
Option Menu like:

Grafik
Bildschirmauflösung einstellen (DropDown)
Vollbild (Checkbox)

Audio
Master (Regler)
SFX (Regler)
Musik (Regler)

Gameplay
N/A

(Copied from User Story 4b)
