### ISSUE TITLE
Collision check on crouch beneath a collidable block

### ISSUE THREAD

**Issue by Firomaeor** [INF19IT2/2d-Jump-n-Run-SE#45]
Currently there's a bug, when you try to "stand up" benath a block, that causes the player to bug into the ground

**Comment by Na1k** [comment]
There needs to be checked, whether the player is allowed to stand up

**Comment by Na1k** [comment]
When you move left/right and jump, the player is horizontally flipped. Instead the Bubbles need to be on top while he jumps up.

**Comment by Na1k** [comment]
@Firomaeor, @rxt30 
Still needed? Because we work with a new Sprite-Asset Set?

**Comment by Firomaeor** [comment]
> 
> 
> When you move left/right and jump, the player is horizontally flipped. Instead the Bubbles need to be on top while he jumps up.

Wrong issue, isn't it? see #42

**Comment by Na1k** [comment]
Crouching does not get implemented
