### ISSUE TITLE
Dummy stops moving

### ISSUE THREAD

**Issue by reusdomi** [INF19IT2/2d-Jump-n-Run-SE#49]
If the player stands in a certain position on the platform between the platform and the dummy, the dummy stops moving, then moves slowly towards the platform and completely stops

**Comment by Florian-0tt** [comment]
When you jump on the dummy and walk over the edge in the direction he is currently moving, he moves slow or stops (when the second spike from the bottem touch the edge), until you pushed them in any direction.
