### ISSUE TITLE
Create a simple Menu

### ISSUE THREAD

**Issue by rxt30** [INF19IT2/2d-Jump-n-Run-SE#5]
Create a simple Menu with the following Buttons:

- Options (starts filler enviroment from the physiks task)
- High-Score (no function)
- Start/Level (no function)
- Exit (Ends programm)

For the background and the title use a filler

**Comment by rxt30** [comment]
I think it would be also useful to set the Menu-Scene as the Main-Scene, as this scene will be the start screen of the game i guess

**Comment by Na1k** [comment]
See #13
