### ISSUE TITLE
Bug on Jump/crouch on enemy dummy. Dummy drops into floor

### ISSUE THREAD

**Issue by Firomaeor** [INF19IT2/2d-Jump-n-Run-SE#53]

**Comment by Firomaeor** [comment]
See #45 for refrence, related Bug, but now on enemy dummy

**Comment by Na1k** [comment]
Related to #49

**Comment by yShizu** [comment]
If you jump and crouch on enemy dummy with the second lower spike touching the dummy's edge, dummy drops up to half into floor.
