### ISSUE TITLE
Scaling 

### ISSUE THREAD

**Issue by Firomaeor** [INF19IT2/2d-Jump-n-Run-SE#62]
User Story 3.4a
--> Exakt pixel figures have to be evaluated with design team

Apply a uniform scale throughout the game and the levels.

- "block" size
- player size
- enemy size 
- etc

**Comment by cedimo** [comment]
Design Team:

Die Skalierung wurde auf 32x32 Pixel festgelegt. 
Die Sprite-Sheets werden jeweils in 32x32 px, 64x64 px und 128x128 px abgegeben. 

Die Skalierung einzelner Elemente:
Gegner 32x64 px
Plattform 32x16 px
Standardblock 32x32 px
