### ISSUE TITLE
[6.4]Rework shoot projectile

### ISSUE THREAD

**Issue by Firomaeor** [INF19IT2/2d-Jump-n-Run-SE#86]
User Story 6.4

"
Bei Betätigung der ??? Taste soll der Spieler ein Projektil schießen können
Das Projektil soll eine Reichweite von 4 Blöcken (128px) haben und dann verschwinden
Der Spieler muss nach dem abfeuern eines Projektils 1 Sekunde warten bis er wieder ein Projektil abschießen kann
Das Projektil soll eine Geschwindigkeit von 32px/Sekunde haben
Sobald das Projektil ein Umgebungs Element trifft, soll es verschwinden
"

**Comment by HannesRosenthal** [comment]
Schießen wird Space zugewiesen. Space kann nicht weiter zum Springen genutzt werden
